Create Connection
payfunc/model-base pull request #24
Opened 2021-08-16 16:01 UTC by Magnus93

2021-08-17 07:18 UTC, robinnedergard requested changes

2021-08-17 07:18 UTC, robinnedergard commented on Connection.ts
> +	async post<Response>(path: string, request: any, format?: true): Promise<Response | gracely.Error> {
Change `format` to `tokenize` again.

2021-08-17 08:52 UTC, robinnedergard approved these changes

2021-08-17 20:33 UTC, marcushanses approved these changes

2021-08-19 07:49 UTC, nilssonemma approved these changes

2021-08-19 11:16 UTC, fredrikbryntesson approved these changes

2021-08-19 11:16 UTC, merged