Connection
payfunc/model-base pull request #36
Opened 2021-08-31 12:20 UTC by marcushanses

2021-08-31 14:59 UTC, Magnus93 submitted a review, later dismissed

2021-08-31 15:16 UTC, nilssonemma approved these changes

2021-09-01 11:25 UTC, robinnedergard requested changes

2021-09-01 11:25 UTC, robinnedergard commented on Connection.ts
> +				a.startsWith("application/json") ? "application/json+camelCase" + a.substring(26) : ""
Why remove all other accept headers than application/json?

2021-09-02 09:25 UTC, nilssonemma submitted a review, later dismissed

2021-09-02 09:30 UTC, robinnedergard approved these changes

2021-09-02 09:32 UTC, fredrikbryntesson approved these changes

2021-09-02 09:33 UTC, merged