Connection parity
payfunc/model-base pull request #37
Opened 2021-08-31 14:13 UTC by marcushanses

2021-08-31 15:09 UTC, Magnus93 submitted a review, later dismissed

2021-08-31 15:45 UTC, nilssonemma requested changes

2021-08-31 15:45 UTC, nilssonemma commented on Connection.ts
> +import * as http from "cloud-http"
import { default as fetch } from "isomorphic-fetch"

2021-09-02 09:26 UTC, nilssonemma approved these changes

2021-09-02 09:32 UTC, fredrikbryntesson approved these changes

2021-09-02 09:33 UTC, merged